[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hellocpp"  # as it would appear on PyPI
version = "0.42"
authors = [ {name = "JP N", email = "n.jayaprakash@intel.com"}]
