[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "greet"  # as it would appear on PyPI
version = "0.42"
authors = [ {name = "Jayaprakash Nevara", email = "jp.shivakavi@gmail.com"}]
